### ISSUE TITLE
Descargar trameros de otros años

### ISSUE THREAD

**Issue by Jes-Lop** [fisabio/medear#5]
Buenas tardes. Trasteando para conseguir importar los trameros del Instituto Nacional de Estadística (INE) me he encontrado con este paquete, que veo muy interesante, aunque todavía lo he investigado muy poco. Veo que puede descargar los tramos hasta 2015 (o al menos yo no he sabido descargar hasta más allá). ¿Sería muy complicado adaptarlo para poder descargar hasta los de este año? Están ya disponibles en la web del instituto entre 2015 y 2021. En todo caso, felicidades por este paquete que me resulta de mucha utilidad. Saludos.

**Comment by carlosvergara** [comment]
Hola,

Sí, es posible descargar hasta el año pasado: he repasado la función porque daba un error al descargar el de 2021 y ya está corregido en la `v.0.8.5`. Si descargas e instalas el paquete de nuevo, podrás descargar todos los trameros disponibles incluyendo 2021. Te pongo un ejemplo para Ceuta (al ser un municipio la descarga es muy rápida):

```
remotes::install_github(repo = "fisabio/medear")
tramero <- medear::descarga_trameros(cod_provincia = "51", years = c(2001, 2004:2021), conservar = FALSE)
```
Un saludo.

**Comment by Aimonius** [comment]
Gracias por la respuesta, sin embargo, al ejecutar el código de prueba me da este error:

`Error in medear::descarga_trameros(cod_provincia = "51", years = c(2001,  : 
  length(years) > 0 & years %in% c(2001, 2004:(as.numeric(format(Sys.time(),  .... are not all TRUE`

Saludos

**Comment by carlosvergara** [comment]
¿Has recordado instalar la última versión del paquete? He probado esa sentencia en Linux y en Windows, y funciona perfectamente. Ejecuta `packageVersion("medear")` y si el resultado no es `"0.8.5"`, instala la última versión del paquete (`remotes::install_github(repo = "fisabio/medear")`).

:)

**Comment by Aimonius** [comment]
Sí, está instalada: `> packageVersion("medear")
[1] ‘0.8.5’`
Igual el problema es que lo estoy ejecutando en Mac...Sigo investigando

**Comment by carlosvergara** [comment]
¿Qué obtienes al ejecutar esto: `as.numeric(format(Sys.time(), "%Y"))`?

**Comment by Aimonius** [comment]
`> as.numeric(format(Sys.time(), "%Y"))
[1] 2021`

**Comment by carlosvergara** [comment]
Pues no veo qué puede pasar... Prueba con la línea completa donde saltaba el error:
```
years <- c(2001, 2004:2021)
stopifnot(length(years) > 0 & years %in% c(2001, 2004:(as.numeric(format(Sys.time(), "%Y")))))
```

Si no saltara un error tras ejecutar lo anterior, prueba a ejecutar la descarga hasta 2020 y luego con 2021:
```
tramero <- medear::descarga_trameros(cod_provincia = "51", years = c(2001, 2004:2020), conservar = FALSE)
tramero <- medear::descarga_trameros(cod_provincia = "51", years = c(2001, 2004:2021), conservar = FALSE)
```
Ya me dices.

**Comment by Aimonius** [comment]
Algo vamos avanzando... `years <- c(2001, 2004:2021)
stopifnot(length(years) > 0 & years %in% c(2001, 2004:(as.numeric(format(Sys.time(), "%Y")))))` no da ningún error

`tramero <- medear::descarga_trameros(cod_provincia = "51", years = c(2001, 2004:2021), conservar = FALSE)` da el error anterior de `Error in medear::descarga_trameros(cod_provincia = "51", years = c(2001,  : 
  length(years) > 0 & years %in% c(2001, 2004:(as.numeric(format(Sys.time(),  .... are not all TRUE`
Sin embargo, `tramero <- medear::descarga_trameros(cod_provincia = "51", years = c(2001, 2004:2020), conservar = FALSE)` se ejecuta perfectamente...

**Comment by carlosvergara** [comment]
Falla precisamente en el parche que introduje esta mañana al actualizar `0.8.4` ->  `0.8.5` para que pillara datos hasta el año en curso. Prueba a instalarlo todo de nuevo pero forzando la instalación, por si hubiera habido algún error en ese punto (me parece raro) y fíjate en si se instala correctamente todo:
```
remotes::install_github(repo = "fisabio/medear", force = TRUE)
tramero <- medear::descarga_trameros(cod_provincia = "51", years = c(2001, 2004:2021), conservar = FALSE)
```

**Comment by Aimonius** [comment]
Sí, todo perfecto ahora, he forzado la instalación, he reiniciado la sesión por si acaso y ahora funciona a la perfección.

Muchísimas gracias @carlosvergara

**Comment by carlosvergara** [comment]
No hay de qué! :)
